---
- name: Setup Webservers
  hosts: webservers

  tasks:
  - name: Install nginx
    yum: name=nginx state=present

  - name: Configure nginx
    template: src=nginx_conf.j2 dest=/etc/nginx/sites-available/site
    notify: reload nginx

  - name: Start nginx
    service: name=nginx state=started enabled=yes

  handlers:
    - name: reload nginx
    service: name=nginx state=reloaded
